apiVersion: apps/v1
kind: Deployment

metadata:
  name: spring-api
  namespace: of-fiap

spec:
  replicas: 2

  selector:
    matchLabels:
      app: spring-api

  template:
    metadata:
      labels:
        app: spring-api

    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:

        - name: spring-api

          image: IMAGE_NAME

          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          env:

            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://localhost:5432/oficina

            - name: SPRING_DATASOURCE_USERNAME
              value: oficina

            - name: SPRING_DATASOURCE_PASSWORD
              value: oficina

            - name: JWT_SECRET
              value: T3Nno4Ipybddv14B1yGQmyl2KudK2dRw91708DQuo2E=



          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"

            limits:
              memory: "512Mi"
              cpu: "500m"

          readinessProbe:

            httpGet:
              path: /actuator/health/readiness
              port: 8080

            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:

            httpGet:
              path: /actuator/health/liveness
              port: 8080

            initialDelaySeconds: 60
            periodSeconds: 20