apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tc-oficina-hpa
  namespace: oficina
  labels:
    app.kubernetes.io/name: tc-oficina
    app.kubernetes.io/part-of: oficina-fiap
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tc-oficina
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
