SELECT * FROM TB_USUARIOS;

SELECT * FROM TB_CLIENTES;

SELECT * FROM TB_VEICULOS;

SELECT * FROM TB_ITEM_ESTOQUE;

SELECT * FROM TB_SERVICOS;

SELECT * FROM TB_ORDENS_SERVICO;

SELECT * FROM TB_ITENS_OS;